import React from "react";
import SearchIcon from "../icons/3.svg";
import SelectIcon from "../icons/1.svg";
import StandoutIcon from "../icons/2.svg";
const Specifics = () => {
  return (
    <div
      id="features-section"
      className="features-section no-large-top slogan-how-work"
    >
      <div className="container">
        <div className="feature-items d-flex-c-c">
          <div className="flex-column item">
            <div className="col image">
              <img alt="Search" src={SearchIcon} />
            </div>
            <div className="title">Search</div>
            <div className="description">
              Simply add a keyword or a term related to your business in the
              slogan maker search box. Wait for the magic to happen.
            </div>
          </div>
          <div className="item">
            <div className="image">
              <img alt="Select" src={SelectIcon} />
            </div>
            <div className="title">Select</div>
            <div className="description">
              Choose from thousands of options generated by the slogan maker
              that fit your needs.
            </div>
          </div>
          <div className="item">
            <div className="image">
              <img alt="Stand out" src={StandoutIcon} />
            </div>
            <div className="title">Showcase</div>
            <div className="description">
              Congrats on your new slogan. It's time to win the world!
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Specifics;
